version: '3.1'

volumes:
  node_backend:


services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: always
    environment:
      PORT: "80"
      SESSION_SECRET: "$SESSION_SECRET"
      GOOGLE_CLIENT_ID: "$GOOGLE_CLIENT_ID"
      GOOGLE_SECRET: "$GOOGLE_SECRET"
      FACEBOOK_CLIENT_ID: "$FACEBOOK_CLIENT_ID"
      FACEBOOK_CLIENT_SECRET: "$FACEBOOK_CLIENT_SECRET"
      TYPEORM_CONNECTION: "$TYPEORM_CONNECTION"
      TYPEORM_HOST: "$TYPEORM_HOST"
      TYPEORM_USERNAME: "$TYPEORM_USERNAME"
      TYPEORM_PASSWORD: "$TYPEORM_PASSWORD"
      TYPEORM_DATABASE: "$TYPEORM_DATABASE"
      TYPEORM_PORT: "$TYPEORM_PORT"
      TYPEORM_SYNCHRONIZE: "false"
      TYPEORM_LOGGING: "false"
      TYPEORM_ENTITIES: "src/entity/**/*.ts"
      TYPEORM_MIGRATIONS: "src/migration/**/*.ts"
      TYPEORM_SUBSCRIBERS: "src/subscriber/**/*.ts"
      TYPEORM_ENTITIES_DIR: "src/entity"
      TYPEORM_MIGRATIONS_DIR: "src/migration"
      TYPEORM_SUBSCRIBERS_DIR: "src/subscriber"
      GOOGLE_CALLBACK: "${URL}/auth/google/callback"
      FACEBOOK_CALLBACK: "${URL}/auth/facebook/callback"
    ports:
      - "${PORT}:80"
    volumes:
      - node_backend:/app/node_modules
